"""Add OrchestratorWorker registry

Revision ID: 194a461733a3
Revises: v004_users_secrets
Create Date: 2026-02-25 04:24:59.651962+00:00

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194a461733a3'
down_revision: Union[str, None] = 'v004_users_secrets'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orchestrator_workers',
    sa.Column('worker_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    with op.batch_alter_table('orchestrator_workers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orchestrator_workers_last_heartbeat_at'), ['last_heartbeat_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orchestrator_workers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orchestrator_workers_last_heartbeat_at'))

    op.drop_table('orchestrator_workers')
    # ### end Alembic commands ###
